# Файл docker-compose.yml

# Версия docker-compose:
version: '3'

# Перечень контейнеров:
services:
  # Контейнер с базой данных
  postgres:
    image: postgres:13.10      # Версия образа PostgreSQL
    env_file: .env             # Файл с переменными окружения
    volumes:
      - pg_data:/var/lib/postgresql/data  
  
  # Контейнер с бэкендом
  backend:
    image: fuller2113/kittygram_backend:latest
    env_file: .env             # Файл с переменными окружения
    depends_on:
      - postgres                # Зависимость от контейнера postgres

  # Контейнер с фронтендом
  frontend:
    image: fuller2113/kittygram_frontend:latest
    env_file: .env             # Файл с переменными окружения

  # Контейнер с Nginx
  nginx:
    image: nginx:latest        # Последняя версия образа Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Конфигурация Nginx
      - ./backend/static:/app/static                   # Статические файлы
      - ./backend/media:/app/media                     # Медиа файлы
    ports:
      - "80:80"                # Прокси для порта 80
    depends_on:
      - backend                 # Обеспечиваем порядок запуска

  # Второй контейнер с базой данных
  db:
    image: postgres:latest     # Образ для базы данных
    environment:
      POSTGRES_DB: Kitty_db    # Имя базы данных
      POSTGRES_USER: rita       # Имя пользователя
      POSTGRES_PASSWORD: Zaq21412 # Пароль пользователя
    volumes:
      - db_data:/var/lib/postgresql/data  # Подключаем volume для данных базы данных

# Определение volume
volumes:
  pg_data:
  db_data:
