# Файл docker-compose.production.yml

# Версия docker-compose:
version: '3'

# Перечень контейнеров:
services:
  # Контейнер с базой данных
  postgres:
    image: postgres:13.10      # Версия образа PostgreSQL
    env_file: .env             # Файл с переменными окружения
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Контейнер с бэкендом
  backend:
    image: fuller2113/kittygram_backend:latest
    env_file: .env             # Файл с переменными окружения
    depends_on:
      - postgres                # Зависимость от контейнера postgres

  # Контейнер с фронтендом
  frontend:
    image: fuller2113/kittygram_frontend:latest
    env_file: .env             # Файл с переменными окружения
    volumes:
      - frontend_build:/app/build/

  # Контейнер с Nginx
  nginx:
    image: fuller2113/kittygram_gateway:latest        # Последняя версия образа Nginx
    volumes:
      - static:/app/static                   # Статические файлы
      - media:/app/media                     # Медиа файлы
      - frontend_build:/app/build/
    ports:
      - "80:80"                # Прокси для порта 80
    depends_on:
      - backend                 # Обеспечиваем порядок запуска

# Определение volume
volumes:
  pg_data:
  static:
  media:
  frontend_build:
