name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest

      - name: Build and push Docker images
        run: |
          docker build -t username/kittygram_backend ./backend
          docker build -t username/kittygram_frontend ./frontend
          docker push username/kittygram_backend
          docker push username/kittygram_frontend

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd ~/kittygram && docker-compose down && git pull && docker-compose up -d --build"
